// Serverless function — IPFS Upload + NFT Mint
// NOW USING WEB3.JS FOR PROPER TRANSACTION SIGNING

import { ethers } from 'ethers';

export default async function handler(req, res) {
    console.log('[publish] Starting...');
    
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const {
            nft_title,
            nft_description,
            session_id,
            log_hash,
            dominant_movement,
            movement_confidence,
            emotion_tag,
            visual_keywords,
            laban_scores,
            prev_log_hash
        } = req.body || {};

        console.log('[publish] Got request:', { nft_title, session_id, dominant_movement });

        const pinataApiKey = process.env.PINATA_API_KEY;
        const pinataSecret = process.env.PINATA_SECRET_KEY;
        const walletKey = process.env.WALLET_PRIVATE_KEY;
        const contractAddress = process.env.NFT_CONTRACT_ADDRESS;
        const rpcUrl = process.env.BASE_RPC_URL || 'https://ethereum-sepolia-rpc.publicnode.com';

        let ipfsCid = null;
        let ipfsUrl = null;
        let ipfsGatewayUrl = null;
        let txHash = null;
        let txUrl = null;

        // 1. Upload to IPFS (Pinata)
        if (pinataApiKey && pinataSecret) {
            console.log('[publish] Uploading to IPFS...');
            const metadata = {
                name: nft_title || 'SomaAgent Study',
                description: nft_description || 'Generated by SomaAgent',
                image: 'ipfs://QmSomaAgentPlaceholder',
                external_url: 'https://videodanza-nft.vercel.app',
                attributes: [
                    {"trait_type": "Dominant Movement", "value": dominant_movement || 'unknown'},
                    {"trait_type": "Emotion", "value": emotion_tag || 'unknown'},
                    {"trait_type": "Confidence", "value": movement_confidence ? (movement_confidence * 100).toFixed(0) + '%' : 'unknown'},
                    {"trait_type": "Agent", "value": "SomaAgent"},
                    {"trait_type": "Session", "value": (session_id || '').slice(0, 8)},
                    {"trait_type": "Log Hash", "value": log_hash ? log_hash.slice(0, 16) + '...' : 'unknown'}
                ],
                soma_agent: {
                    session_id: session_id,
                    laban_scores: laban_scores || {},
                    visual_keywords: visual_keywords || [],
                    agent_log_hash: log_hash,
                    created_at: new Date().toISOString()
                }
            };

            try {
                const pinataResp = await fetch('https://api.pinata.cloud/pinning/pinJSONToIPFS', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'pinata_api_key': pinataApiKey,
                        'pinata_secret_api_key': pinataSecret
                    },
                    body: JSON.stringify({
                        pinataContent: metadata,
                        pinataMetadata: { name: nft_title || 'SomaAgent NFT' }
                    }),
                    timeout: 10000
                });

                if (pinataResp.ok) {
                    const pinataData = await pinataResp.json();
                    ipfsCid = pinataData.IpfsHash;
                    ipfsUrl = `ipfs://${ipfsCid}`;
                    ipfsGatewayUrl = `https://black-persistent-fly-380.mypinata.cloud/ipfs/${ipfsCid}`;
                    console.log('[publish] IPFS success:', ipfsCid);
                } else {
                    console.log('[publish] IPFS failed:', pinataResp.status);
                }
            } catch (ipfsErr) {
                console.log('[publish] IPFS error:', ipfsErr.message);
            }
        }

        // 2. Mint NFT using ethers.js + web3 signing
        if (walletKey && contractAddress && ipfsUrl) {
            console.log('[publish] Starting blockchain mint...');
            try {
                // Verify ethers is available
                if (!ethers || !ethers.JsonRpcProvider) {
                    throw new Error('ethers.js not loaded properly');
                }
                
                // Connect to RPC
                console.log('[publish] Connecting to RPC:', rpcUrl);
                const provider = new ethers.JsonRpcProvider(rpcUrl);
                console.log('[publish] Creating wallet from private key...');
                const wallet = new ethers.Wallet(walletKey, provider);
                
                console.log('[publish] Wallet address:', wallet.address);
                console.log('[publish] Contract address:', contractAddress);

                // Get chain ID to verify network
                const network = await provider.getNetwork();
                console.log('[publish] Connected to chain:', network.chainId);

                // Contract ABI for mint - matches SomaArt.sol: function mint(address to, string memory uri)
                const contractABI = [
                    'function mint(address to, string memory uri) public returns (uint256)'
                ];

                const contract = new ethers.Contract(contractAddress, contractABI, wallet);

                // Get nonce
                console.log('[publish] Fetching nonce...');
                const nonce = await provider.getTransactionCount(wallet.address);
                console.log('[publish] Nonce:', nonce);
                
                console.log('[publish] Fetching gas price...');
                // ethers v6: use getFeeData() instead of getGasPrice()
                const feeData = await provider.getFeeData();
                const maxFeePerGas = feeData.maxFeePerGas || ethers.parseUnits('20', 'gwei');
                const maxPriorityFeePerGas = feeData.maxPriorityFeePerGas || ethers.parseUnits('1', 'gwei');
                console.log('[publish] Max fee per gas:', ethers.formatUnits(maxFeePerGas, 'gwei'), 'gwei');
                console.log('[publish] Max priority fee:', ethers.formatUnits(maxPriorityFeePerGas, 'gwei'), 'gwei');

                // Estimate gas
                console.log('[publish] Estimating gas for mint call...');
                try {
                    const gasEstimate = await contract.mint.estimateGas(wallet.address, ipfsUrl);
                    console.log('[publish] Gas estimate:', gasEstimate.toString());
                } catch (estimateErr) {
                    console.log('[publish] Gas estimate failed (will use fixed):', estimateErr.message);
                }

                // Build and send transaction
                console.log('[publish] Calling mint(' + wallet.address + ', ' + ipfsUrl + ')');
                const tx = await contract.mint(wallet.address, ipfsUrl, {
                    gasLimit: 300000n,
                    maxFeePerGas: maxFeePerGas,
                    maxPriorityFeePerGas: maxPriorityFeePerGas
                });

                txHash = tx.hash;
                txUrl = `https://sepolia.etherscan.io/tx/${txHash}`;

                console.log('[publish] ✅ TX SENT:', txHash);
                console.log('[publish] Explorer:', txUrl);

            } catch (mintErr) {
                console.log('[publish] ❌ MINT ERROR:', mintErr.message);
                console.log('[publish] Error code:', mintErr.code);
                console.log('[publish] Stack:', mintErr.stack);
                
                // Return IPFS data even if mint failed
                txHash = 'pending_mint_' + Math.random().toString(36).slice(7);
                txUrl = null;
            }
        } else {
            console.log('[publish] Missing config: wallet=', !!walletKey, 'contract=', !!contractAddress, 'ipfs=', !!ipfsUrl);
            txHash = 'not_configured';
        }

        const result = {
            status: 'published',
            ipfs_cid: ipfsCid,
            ipfs_url: ipfsUrl,
            ipfs_gateway_url: ipfsGatewayUrl,
            tx_hash: txHash,
            tx_url: txUrl
        };
        
        console.log('[publish] Returning:', result);
        return res.status(200).json(result);

    } catch (error) {
        console.error('[publish] Fatal error:', error.message);
        return res.status(500).json({
            error: error.message || 'Publish failed',
            tx_hash: null,
            status: 'error'
        });
    }
}
