// Serverless function — IPFS Upload + NFT Mint
// NOW USING WEB3.JS FOR PROPER TRANSACTION SIGNING

import { ethers } from 'ethers';

export default async function handler(req, res) {
    console.log('[publish] Starting...');
    
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        const {
            nft_title,
            nft_description,
            session_id,
            log_hash
        } = req.body || {};

        console.log('[publish] Got request:', { nft_title, session_id });

        const pinataApiKey = process.env.PINATA_API_KEY;
        const pinataSecret = process.env.PINATA_SECRET_KEY;
        const walletKey = process.env.WALLET_PRIVATE_KEY;
        const contractAddress = process.env.NFT_CONTRACT_ADDRESS;
        const rpcUrl = process.env.BASE_RPC_URL || 'https://ethereum-sepolia-rpc.publicnode.com';

        let ipfsCid = null;
        let ipfsUrl = null;
        let ipfsGatewayUrl = null;
        let txHash = null;
        let txUrl = null;

        // 1. Upload to IPFS (Pinata)
        if (pinataApiKey && pinataSecret) {
            console.log('[publish] Uploading to IPFS...');
            const metadata = {
                name: nft_title || 'SomaAgent Study',
                description: nft_description || 'Generated by SomaAgent',
                image: 'ipfs://QmSomaAgentPlaceholder',
                attributes: [
                    {"trait_type": "Agent", "value": "SomaAgent"},
                    {"trait_type": "Session", "value": (session_id || '').slice(0, 8)},
                ]
            };

            try {
                const pinataResp = await fetch('https://api.pinata.cloud/pinning/pinJSONToIPFS', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'pinata_api_key': pinataApiKey,
                        'pinata_secret_api_key': pinataSecret
                    },
                    body: JSON.stringify({
                        pinataContent: metadata,
                        pinataMetadata: { name: nft_title || 'SomaAgent NFT' }
                    }),
                    timeout: 10000
                });

                if (pinataResp.ok) {
                    const pinataData = await pinataResp.json();
                    ipfsCid = pinataData.IpfsHash;
                    ipfsUrl = `ipfs://${ipfsCid}`;
                    ipfsGatewayUrl = `https://black-persistent-fly-380.mypinata.cloud/ipfs/${ipfsCid}`;
                    console.log('[publish] IPFS success:', ipfsCid);
                } else {
                    console.log('[publish] IPFS failed:', pinataResp.status);
                }
            } catch (ipfsErr) {
                console.log('[publish] IPFS error:', ipfsErr.message);
            }
        }

        // 2. Mint NFT using ethers.js + web3 signing
        if (walletKey && contractAddress && ipfsUrl) {
            console.log('[publish] Starting blockchain mint...');
            try {
                // Connect to RPC
                const provider = new ethers.JsonRpcProvider(rpcUrl);
                const wallet = new ethers.Wallet(walletKey, provider);
                
                console.log('[publish] Wallet:', wallet.address.slice(0, 10) + '...');

                // Contract ABI for mint
                const contractABI = [
                    'function mint(address to, string memory uri) public returns (uint256)'
                ];

                const contract = new ethers.Contract(contractAddress, contractABI, wallet);

                // Get nonce
                const nonce = await provider.getTransactionCount(wallet.address);
                const gasPrice = await provider.getGasPrice();
                
                console.log('[publish] Nonce:', nonce, 'Gas price:', ethers.formatUnits(gasPrice, 'gwei'), 'gwei');

                // Estimate gas
                const gasEstimate = await contract.mint.estimateGas(wallet.address, ipfsUrl);
                console.log('[publish] Gas estimate:', gasEstimate.toString());

                // Build and send transaction
                console.log('[publish] Sending mint transaction...');
                const tx = await contract.mint(wallet.address, ipfsUrl, {
                    gasLimit: gasEstimate.mul(110n).div(100n), // 10% buffer
                    gasPrice: gasPrice,
                    nonce: nonce
                });

                txHash = tx.hash;
                txUrl = `https://sepolia.etherscan.io/tx/${txHash}`;

                console.log('[publish] TX SENT:', txHash);
                console.log('[publish] Explorer:', txUrl);

                // Don't wait for receipt - return immediately
                // Transaction is already in mempool

            } catch (mintErr) {
                console.log('[publish] Mint error:', mintErr.message);
                // Return IPFS data even if mint failed
                txHash = 'pending_mint_' + Math.random().toString(36).slice(7);
                txUrl = null;
            }
        } else {
            console.log('[publish] Missing: wallet=', !!walletKey, 'contract=', !!contractAddress, 'ipfs=', !!ipfsUrl);
            txHash = 'not_configured';
        }

        const result = {
            status: 'published',
            ipfs_cid: ipfsCid,
            ipfs_url: ipfsUrl,
            ipfs_gateway_url: ipfsGatewayUrl,
            tx_hash: txHash,
            tx_url: txUrl
        };
        
        console.log('[publish] Returning:', result);
        return res.status(200).json(result);

    } catch (error) {
        console.error('[publish] Fatal error:', error.message);
        return res.status(500).json({
            error: error.message || 'Publish failed',
            tx_hash: null,
            status: 'error'
        });
    }
}
