"""
SomaAgent v2 — Shared Agent State
LangGraph state flows through all nodes.
"""
from typing import TypedDict, Optional, List, Dict, Any


class AgentState(TypedDict):
    # ─── Perception ───────────────────────────────────────────
    raw_landmarks: Optional[List[Dict]]      # MediaPipe landmarks per frame
    laban_scores: Optional[Dict[str, float]] # {"golpear": 0.8, "flotar": 0.2, ...}
    dominant_movement: Optional[str]          # "golpear"
    movement_confidence: Optional[float]     # 0.87

    # ─── Reasoning ────────────────────────────────────────────
    reasoning_chain: Optional[List[str]]     # LLM's thought steps
    artistic_interpretation: Optional[str]   # Poetic text generated by LLM
    nft_title: Optional[str]                 # Title the agent chose
    nft_description: Optional[str]           # Description the agent wrote
    visual_keywords: Optional[List[str]]     # ["explosive", "geometric", ...]
    emotion_tag: Optional[str]               # "intensity", "serenity", etc.
    should_mint: Optional[bool]              # Autonomous decision: mint this NFT?

    # ─── Log (ERC-8004) ───────────────────────────────────────
    session_id: Optional[str]               # UUID for this session
    log_entries: Optional[List[Dict]]       # Full decision chain
    log_hash: Optional[str]                 # SHA-256 hash of the log
    prev_log_hash: Optional[str]            # Hash chain (links to previous)

    # ─── Publish ──────────────────────────────────────────────
    ipfs_cid: Optional[str]                 # IPFS content ID
    ipfs_url: Optional[str]                 # ipfs://... URL
    tx_hash: Optional[str]                  # NFT mint transaction
    tx_url: Optional[str]                   # Explorer URL for the tx

    # ─── Auctions (SuperRare / RARE Protocol) ──────────────────
    token_id: Optional[int]                 # ERC-721 token ID from mint
    auction_tx: Optional[str]               # Auction creation transaction
    auction_enabled: Optional[bool]         # Whether auctions are enabled

    # ─── Control ──────────────────────────────────────────────
    error: Optional[str]                    # Error message if any node fails
    status: Optional[str]                   # "running" | "done" | "error"
    next_action: Optional[str]              # LangGraph routing hint
