// Serverless function — LLM artistic interpretation
// Requires env var: OLLAMA_API_KEY

const NFT_FALLBACK = {
    golpear:   { title: 'Crimson Impact, Bound',    emotion: 'fury' },
    flotar:    { title: 'Ethereal Drift',            emotion: 'peace' },
    deslizar:  { title: 'Metallic Glide',            emotion: 'serenity' },
    cortar:    { title: 'Brutalist Edge',            emotion: 'tension' },
    presionar: { title: 'Tectonic Weight',           emotion: 'power' },
    retorcer:  { title: 'Bioluminescent Spiral',     emotion: 'mystery' },
    sacudir:   { title: 'Trembling Energy',          emotion: 'dynamic' },
    tocar:     { title: 'Ink Pointillism',           emotion: 'curiosity' }
};

export default async function handler(req, res) {
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const { movement, scores, confidence } = req.body || {};

    if (!movement) {
        return res.status(400).json({ error: 'movement required' });
    }

    const apiKey = process.env.OLLAMA_API_KEY;

    if (!apiKey) {
        // Graceful fallback — no key configured
        const fb = NFT_FALLBACK[movement] || NFT_FALLBACK.sacudir;
        return res.status(200).json({
            nft_title: fb.title,
            description: `${movement} movement expressing ${fb.emotion}. SomaAgent v2.`,
            emotion_tag: fb.emotion,
            source: 'fallback'
        });
    }

    try {
        const prompt = `You are an AI artist agent. A human just moved with this Laban quality: "${movement}" (confidence: ${(confidence * 100).toFixed(1)}%).

Generate a short, poetic NFT title (max 5 words) and a 1-sentence description for artwork inspired by this movement.

Respond ONLY with JSON: {"nft_title": "...", "description": "...", "emotion_tag": "..."}`;

        const response = await fetch('https://api.ollama.com/api/chat', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'Authorization': `Bearer ${apiKey}`
            },
            body: JSON.stringify({
                model: 'glm-5',
                messages: [{ role: 'user', content: prompt }],
                stream: false,
                options: { temperature: 0.8, max_tokens: 150 }
            })
        });

        if (!response.ok) throw new Error(`LLM error: ${response.status}`);

        const data = await response.json();
        const content = data.message?.content || data.choices?.[0]?.message?.content || '';

        // Parse JSON from response
        const jsonMatch = content.match(/\{[^}]+\}/s);
        if (!jsonMatch) throw new Error('No JSON in response');

        const parsed = JSON.parse(jsonMatch[0]);
        return res.status(200).json({ ...parsed, source: 'llm' });

    } catch (e) {
        // Fallback on any LLM error
        const fb = NFT_FALLBACK[movement] || NFT_FALLBACK.sacudir;
        return res.status(200).json({
            nft_title: fb.title,
            description: `${movement} movement expressing ${fb.emotion}. Generated by SomaAgent v2.`,
            emotion_tag: fb.emotion,
            source: 'fallback',
            error: e.message
        });
    }
}
